### ISSUE TITLE
Connecting to mysql container

### ISSUE THREAD

**Issue by jeremymcjunkin** [monsooncommerce/monsoon-samples#4]
I am trying to get my lambda connecting to my mysql container with docker-compose from my lambda with sam-local.  Typically, I am able to access the database with the name of the mysql service, ie: `mysql`, but I get an error saying it's not found.
```
lambda_1           | 2019-06-26T12:55:40.591Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	{ Error: getaddrinfo ENOTFOUND    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
lambda_1           |     --------------------
lambda_1           |     at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:144:48)
lambda_1           |     at Protocol.handshake (/var/task/node_modules/mysql/lib/protocol/Protocol.js:51:23)
lambda_1           |     at PoolConnection.connect (/var/task/node_modules/mysql/lib/Connection.js:119:18)
lambda_1           |     at Pool.getConnection (/var/task/node_modules/mysql/lib/Pool.js:48:16)
lambda_1           |     at /var/task/node_modules/typeorm/driver/mysql/MysqlDriver.js:764:18
lambda_1           |     at new Promise (<anonymous>)
lambda_1           |     at MysqlDriver.createPool (/var/task/node_modules/typeorm/driver/mysql/MysqlDriver.js:761:16)
lambda_1           |     at MysqlDriver.<anonymous> (/var/task/node_modules/typeorm/driver/mysql/MysqlDriver.js:274:51)
lambda_1           |     at step (/var/task/node_modules/tslib/tslib.js:133:27)
lambda_1           |     at Object.next (/var/task/node_modules/tslib/tslib.js:114:57)
lambda_1           |   errno: 'ENOTFOUND',
lambda_1           |   code: 'ENOTFOUND',
lambda_1           |   syscall: 'getaddrinfo',
lambda_1           |   hostname: 'mysql',
lambda_1           |   host: 'mysql',
lambda_1           |   port: '3306',
lambda_1           |   fatal: true }
```
Below is my docker-compose file.
```
version: '3.6'
services:
  lambda_yarn_app:
    image: lambci/lambda:build-nodejs10.x
    volumes:
      - ../:/var/task

  lambda:
    build:
      context: .
      dockerfile: Dockerfile.sam
      args:
        PORT: '3001'
        SAM_CMD: start-lambda
    # we depend on the mysql backend
    depends_on:
      - mysql
    environment:
      - TYPEORM_HOST=mysql
      - TYPEORM_PORT=3306
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: ["$PWD"]
    ports:
      - "3001:3001"
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: .
      dockerfile: Dockerfile.sam
      args:
        PORT: '3000'
        SAM_CMD: start-api
    # we depend on the mysql backend
    depends_on:
      - mysql
    command: ["$PWD"]
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
      
  mysql:
    # just using the base image
    image: mysql:5.6
    container_name: mysql
    # map the container port 3306 back to port 3333 on our host
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: theusername
      MYSQL_PASSWORD: thepw
      MYSQL_DATABASE: subscription
    # the *.sql files in this dir will be run when the volume is first created
    volumes:
      - ./data:/docker-entrypoint-initdb.d
          
```

I found an example here: https://github.com/JontyC/SAM-Docker-MySQL/blob/master/docker-compose.yml, but it's using an outdated version of docker-compose.

**Comment by jeremymcjunkin** [comment]
I figured out the issue.  If my understanding is correct, SAM local starts another container inside the container for the lambda to run in.  This does not explicitly have access to the network, so it needs to be defined.

By defining the network in my docker-compose.yml file, my lambda was able to access my mysql container via host `mysql`.

```
networks:
  default:
    external:
      name: sam_default
```
